### ISSUE TITLE
System.getProperty doesn't emit goog.require

### ISSUE THREAD

**Issue by niloc132** [google/j2cl#1]
Observed in jsinterop-base, where jsinterop.js contains the following:
```
/**
 * This file provides the @defines for jsinterop configuration options.
 * See InternalPreconditions.java for details.
 */

goog.provide('jsinterop');

// Note that disabling checking only disables it for production.

/** @define {string} */
goog.define('jsinterop.checks', 'DISABLED');
```

Then, InternalPreconditions.java uses this:
```
private static final boolean IS_TYPE_CHECKED = 
                getProperty("jsinterop.checks").equals("ENABLED");
```

Currently, System.getProperty is implemented with JsMethod for J2CL (and a magic method for gwt2):
```
  @JsMethod(name = "$getDefine", namespace = "nativebootstrap.Util")
  public static native String getProperty(String key);
```

The Util.$getDefine method only calls `goog.getObjectByName` with the parameter, not a compiletime string, and closure-compiler doesn't seem to be able to detect this anyway. 

The result is a runtime NPE in both BUNDLE and ADVANCED compilation modes, unless jsinterop.js is manually added as an `--entry_point`, or a new define is added to the build directly (and in that case, `--define` isn't used by BUNDLE, by design).

Historically, it looks like J2CL used to have a pass which would examine System.getProperty calls and do something with them - perhaps the same idea could be used again to emit `goog.require` calls to correctly require that non-native.js files are loaded. 

This might be worth generalizing, so that non-native.js files can be depended on in general? It would add an extra step to use a system property which isn't ideal, but does prevent the need for j2cl to recognize specific pieces of code to be transpiled.

This would also allow `jre.js` to keep working if classMetadata and checkedMode were moved - while there is a `goog.provide('jre.checks')` in that file, nothing actually ever depends on jre.checks, so could stop working if the file were split into one file per `provide`.

**Comment by jDramaix** [comment]
@concavelenz @gkdn  any update?

**Comment by gkdn** [comment]
This doesn't need an update, could stay as a known issue.

**Comment by gkdn** [comment]
Since there is not much we can do here I'm closing the issue.
https://github.com/google/j2cl/issues/76 tracks the documentation/example/macro.
