### ISSUE TITLE
strings, nulls, and concatenation result in seemingly unnecessary compiled code

### ISSUE THREAD

**Issue by niloc132** [google/j2cl#104]
**Is your feature request related to a problem? Please describe.**
String concatenation results in an extra String.valueOf(...) wrapper around each String reference, even if that string cannot be null. We observed this from a simple program like this:
```
    public static void go() {
        String b = "b";
        DomGlobal.alert("a" + b + cd() + e() + f());
    }
    public static String cd() {
        return "c" + d();
    }

    @JsMethod(namespace = JsPackage.GLOBAL, name = "foo")
    public static native String d();
    @JsMethod(namespace = JsPackage.GLOBAL, name = "bar")
    public static native String e();

    @JsProperty(namespace = JsPackage.GLOBAL, name = "baz")
    public static native String f();
```

J2cl compiled output
```
function () {
        l.alert("ab" + String("c" + p(foo())) + p(bar()) + p(baz))
    }
```

GWT2 output, for reference:
```
    function Sc() {
        $wnd.goog.global.alert('ab' + ('c' + $wnd.foo()) + $wnd.bar() + $wnd.baz)
    }
```

The `p` method is the `java.lang.String.valueOf(Object)`, which is being used to manage the possibility of `undefined` values being normalized correctly to a `"null"` string. Note that adding @JsNonNull to the three native methods or to the `cd()` method has no effect.

From my perspective, at least `cd()` should be left unwrapped by `String`, since it clearly cannot return a value other than a string - this might be a limitation in closure though.

--

Here's another example, this time avoiding `native` and sticking with a class hierarchy, which seems to prevent closure from doing some kinds of optimizations. The effect is more pronounced here, gwt2 understands this code much more clearly:
```
    @JsMethod
    public void go() {
        DomGlobal.alert(
                new Superclass().string() + new OtherConstant().string() + new CallsSuper().string() + new Dynamic("e").string()
        );
    }
    public static class Superclass {
        public String string() {
            return "a";
        }
    }
    public static class OtherConstant extends Superclass {
        @Override
        public String string() {
            return "b";
        }
    }
    public static class CallsSuper extends Superclass {
        @Override
        public String string() {
            return super.string() + "d";
        }
    }
    public static class Dynamic extends Superclass {
        private final String value;

        public Dynamic(String value) {
            this.value = value;
        }

        @Override
        public String string() {
            return value;
        }
    }
```

J2cl compiled output, abbreviated to omit the types beyond the first one - the important thing for this issue is that each returned string value is wrapped in `r(...)`:
```
    function () {
        n.alert(r((new y).a()) + r((new C).a()) + r((new z).a()) + r(B().a()))
    }
    //...
    function r(a) {//java.lang.String.valueOf
        if (null == a) a = "null"; else if (Array.isArray(a)) {
            var b = a.h;
            a = t(b ? u(b.j, b.i) : u(q, 1)) + "@" + (v(a) >>> 0).toString(16)
        } else a = a.toString();
        return a
    };
    //...
    function y() {
    }
    m(y, q);
    y.prototype.a = function () {
        return "a"
    };
    y.prototype.b = ["org.example.App$Superclass", 0];
    // etc
```

Full GWT2 output of the code in question:
```
    function Tc() {
        $wnd.goog.global.alert('abad' + (new Re).a)
    }
    //...
    function Re() {
        this.a = 'e'
    }
```

As above, the important thing for this issue is the String.valueOf wrapping (not the fact that closure-compiler can't understand and compile out the subclasses which could be finalized, staticified, and inlined in gwt2 terms, which I plan to address separately as I understand it better). Instead, I'd like to focus here on the `p` method in the first example, the `r` method in the second case - the use of String.valueOf to wrap all potentially null string values. From `InsertStringConversions`:
```
/**
 * Inserts a Strings.valueOf() operation when a non-string type is part of a "+" operation along
 * with the string type in a string conversion context.
 */
public class InsertStringConversions extends NormalizationPass {
```
This comment is a bit misleading, since it also inserts [String].valueOf operations for strings which aren't a) literals, or b) binary operations like `+` (where the each constituent child has also been wrapped in this way:
```
        TypeDescriptor typeDescriptor = expression.getTypeDescriptor();
        if (expression.isNonNullString()) {
          return expression;
        }

        // Normally Java would call String.valueOf on a primitive but there is no need in J2CL
        // because JS converts primitives to String in the presence of a + operator.
        // We make an exception for Char which is represented as a JS number and hence needs to
        // be explicitly converted.
        // NOTE: Primitive longs are not represented as primitives in JS but are implemented as
        // instances of a class where we can rely on toString().
        if (TypeDescriptors.isNonVoidPrimitiveType(typeDescriptor)
            && !TypeDescriptors.isPrimitiveChar(typeDescriptor)) {
          return expression;
        }

        // For the normal case we call String.valueOf which performs the right conversion.
        return MethodCall.Builder.from(getStringValueOfMethodDescriptor(typeDescriptor))
            .setArguments(expression)
            .build();
```
Any "nullable" string then gets this String.valueOf wrapper, which appears to only refer to string literals, and existing BinaryOperations which return a string.

**Describe the solution you'd like**
One weaker option would be to update the `isNonNullString` check with simply a "is this already a String" check, but this would allow some `undefined` values to be made into "undefined" instead of "null" - I'm not sure that is acceptable, but I'm guessing that it isn't - I'm only offering it as the first guess I would make here.

This doesn't quite work as I would expect though, as closure warns now that some vars which are expected to be strings now might be numbers. Here's the generated .impl.java.js:
```
 /** @return {?string} */
 static m_valueOf__java_lang_String(/** ?string */ val) {
  j_l_String.$clinit();
  return $Equality.$same(val, null) ? "null" : val;
 }
```
and the usage, here in Class.impl.java.js:
```
  /** @return {?string} */
 m_getCanonicalName__() {
  return $Overlay.m_getClassName__$devirt__javaemul_internal_Constructor(this.f_ctor__java_lang_Class_) + Class.m_repeatString__java_lang_String__int("[]", this.f_dimensionCount__java_lang_Class_);
 }
```
```
/home/colin/.m2/repository/com/vertispan/j2cl/jre/0.8-SNAPSHOT/jre-0.8-SNAPSHOT-jszip.zip!/java/lang/Class.impl.java.js:53: 
Originally at:
/home/colin/.m2/repository/com/vertispan/j2cl/jre/0.8-SNAPSHOT/jre-0.8-SNAPSHOT-jszip.zip!/java/lang/Class.java:70: WARNING - [JSC_TYPE_MISMATCH] inconsistent return type
found   : (number|string)
required: (null|string)
```
Perhaps closure is relying on the `stringInstance.toString()` call for some reason?

The output is closer to what I would naively expect though:
```
function () {
        n.alert((new y).a() + (new C).a() + (new z).a() + B().a())
    }
```

**Describe alternatives you've considered**
One experiment I did was to introduce a String.valueOf(String) method in the JRE, which consists only of a ternary, under the hope that this would convince closure that the method could be inlined and the `null`/`undefined` case removed since the value can never be null. This had the effect though of only replacing the `r` function, but the compiler still didnt peek inside and see that the possible return values can never be null, so the check isn't necessary.
```
    function r(a) {
        return null == a ? "null" : a
    };
```

I also tried to replace the String.valueOf() wrapper (existing expression plus min of three bytes) with something like `someMethod() ?? "null"`, which too should compile out to three extra bytes, but might be easier for the compiler to optimize, but J2CL doesn't support this in its AST yet. For the same basic effect, I also tried to synthesize a ternary, thought this would generate a lot more core, but this also did not clarify to the compiler what we wanted.

Both of these result in the same compiler warnings as above.

**Comment by gkdn** [comment]
J2clStringValueOfRewriterPass is the JsCompiler pass that does the necessary optimizations.
If it is missing something some simple cases, you can send a patch for it.

**Comment by niloc132** [comment]
Perfect, thanks for the pointer - that's exactly where I needed to be! With a two line change there, I have almost all of the rest of the app compiled away, just a bit more than this remains from the first sample... provided the externs for foo/bar/baz mark them as non-nullable:
```
    function () {
        a.alert("abc" + foo() + bar() + baz)
    }
```
Marking just foo as non-nullable for example results in this (plus all the String.value of wiring, which includes a lot of Class itself):
```
    function () {
        l.alert("abc" + foo() + p(bar()) + p(baz))
    }
```
I'll run the existing tests and see about writing my own to confirm that this is what we expect, and submit a PR over at closure-compiler.

--

Two follow up questions, if you have a minute:

* Is there a meaningful difference in JS I'm missing between `"null"` and `String('null')`? It appears that the first is the output for a `undefined`, while the second is what we get for `null` values - in a JS debugger I don't see an obvious reason for the difference though.
* Do we expect `@JsNonNull` to have an impact on the generated JS? The annotation isn't mentioned at https://github.com/google/j2cl/blob/master/docs/jsinterop-by-example.md

**Comment by gkdn** [comment]
I'm not sure if I understand your first question but output for a `undefined` in JS is `"undefined"` but there is no different between `"null"` and `String(null)` or `String("null")` which are all equal to `"null"`.

wrt JsNonNull;
It changes the output type to be non-nullable (e.g. `!Object` in Closure). That has effect on type checking in JsCompiler but not on optimizations.

**Comment by niloc132** [comment]
Thanks, the first is what I expected, still trying to see how the second behaves. I'll follow up further on the closure compiler discussion mailing list to make sure my patches meet expectations, conventions.
