### ISSUE TITLE
Choosing Java Standard Library source and version

### ISSUE THREAD

**Issue by ScraM-Team** [google/j2cl#112]
Which version of the Java Standard Library is used by default in J2CL?  Is it:
* A bundled version?
* The version in the JRE used during the build?

If we want to use a different version of the class library, how do we specify where to find the class files?

**Comment by tbroyer** [comment]
J2CL uses its own version that it translates to JS too. When compiling your classes with JavaC, it needs to be used as the bootstrap classpath (or a system image with JDK 9+).
(This is all taken care of for you when using J2CL through Bazel)

**Comment by ScraM-Team** [comment]
Where is source for the J2CL version of the standard library?  I looked in j2cl/jre/java/java but it doesn't seem to be what you are talking about.

**Comment by tbroyer** [comment]
It's shared with GWT for the most part: https://github.com/gwtproject/gwt/tree/master/user/super/com/google/gwt/emul

**Comment by ScraM-Team** [comment]
Thanks!  That'exactly what I was looking for.

**Comment by norzak** [comment]
Sorry to comment to an already closed issue, Can we super-source missing JRE classes like we to in GWT?
