### ISSUE TITLE
Cannot transpile anything, not even the helloworld sample

### ISSUE THREAD

**Issue by vruegner** [google/j2cl#114]
**Describe the bug**
When transpiling the helloworld-sample of the current master branch with the command:

`j2cl/tmp/j2cl/samples/helloworld$ bazel build //src/main/java/com/google/j2cl/samples/helloworld`

i get the following error:

`ERROR: /home/volker/Work/j2cl/tmp/j2cl/samples/helloworld/src/main/java/com/google/j2cl/samples/helloworldlib/BUILD:13:13: //src/main/java/com/google/j2cl/samples/helloworldlib:helloworldlib-j2wasm: invalid label '//src/main/java/com/google/j2cl/samples/helloworldlib/@com_google_j2cl//:jsinterop-annotations-j2wasm' in element 0 of attribute 'deps' in '_j2wasm_library_rule' rule: invalid package name 'src/main/java/com/google/j2cl/samples/helloworldlib/@com_google_j2cl//': package names may not end with '/'
ERROR: /home/volker/Work/j2cl/tmp/j2cl/samples/helloworld/src/main/java/com/google/j2cl/samples/helloworld/BUILD:8:19: Target '//src/main/java/com/google/j2cl/samples/helloworldlib:helloworldlib' contains an error and its package is in error and referenced by '//src/main/java/com/google/j2cl/samples/helloworld:app'`

My own project shows the same error.

**Bazel version**
Build label: 3.7.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:29:16 2020 (1603200556)
Build timestamp: 1603200556
Build timestamp as int: 1603200556

Expected behaviour:
Transpile without error as the version before.

**Comment by gkdn** [comment]
This is broken yesterday, @jDramaix is looking into it.

**Comment by jDramaix** [comment]
I have the fix for review internally. It should be pushed to github soon.

**Comment by vruegner** [comment]
Thank you. Works like a charm :).

**Comment by jDramaix** [comment]
Fixed with aadbb9bf47b38afbcfdef09b2b241d4c8be914e8
