### ISSUE TITLE
Can't build the whole sample workspace

### ISSUE THREAD

**Issue by solomatov** [google/j2cl#12]
**Describe the bug**
Can't build the whole sample workspace

**To Reproduce**
I run bazel build //... in the sample folder. I got the following message:

[kostik@kostik-laptop helloworld]$ bazel build //...
INFO: SHA256 (https://github.com/google/j2cl/archive/master.zip) = b207fe05be1ce2f9f3a48bfa7c1e805045ea6adcc1df51ec7e9822bb5286c66c
ERROR: /home/kostik/Projects/j2cl/samples/helloworld/javatests/com/google/j2cl/samples/helloworldlib/BUILD:3:1: file '@com_google_j2cl//build_defs:rules.bzl' does not contain symbol 'j2cl_test'
ERROR: /home/kostik/Projects/j2cl/samples/helloworld/javatests/com/google/j2cl/samples/helloworldlib/BUILD:5:1: name 'j2cl_test' is not defined (did you mean 'java_test'?)
ERROR: package contains errors: javatests/com/google/j2cl/samples/helloworldlib
ERROR: error loading package 'javatests/com/google/j2cl/samples/helloworldlib': Package 'javatests/com/google/j2cl/samples/helloworldlib' contains errors
INFO: Elapsed time: 2.569s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded)

I tried both zip version and local repo version

**Expected behavior**
Expect it to be build fine.

**Comment by rluble** [comment]
Junit testing (j2cl_test) has not been ported to work in open source yet.

**Comment by solomatov** [comment]
@rluble Are you going to do this soon? It would be nice if you do something about it, since it would be really nice if bazel build //... work across the project.

**Comment by jDramaix** [comment]
We are working on that. For the time being we mention on our README that tests are not supported yet https://github.com/google/j2cl#caveat-emptor
So I'm closing this issue

**Comment by solomatov** [comment]
I think it's much worse not to support bazel //.. than not to support test. It makes is impossible for external people to make contributions. How you can test that your contributions work and old tests pass?

**Comment by jDramaix** [comment]
They cannot util we finish our work on opensourcing the test infrastructure. But we are actively working on that right now.

**Comment by rluble** [comment]
Actually the integration tests work you can run them with 

   bazel test transpiler/javatests/com/google/j2cl/transpiler/integration/...

I think currently only 4 out of the ~200 tests fail.

**Comment by jDramaix** [comment]
To clarify:
 - test used for testing J2CL transpiler work on opensource
 - j2cl_test bazel rule used for testing your application or library written with J2CL is not open source'd yet. We are working on it.

Don't forget that J2CL  is currently in 'alpha' release for developer preview.

**Comment by solomatov** [comment]
When I the command , I got the following error:

[kostik@kostik-laptop j2cl]$ bazel test //transpiler/javatests/com/google/j2cl/transpiler/integration/...
ERROR: /home/kostik/Projects/j2cl/transpiler/javatests/com/google/j2cl/transpiler/integration/box2d/BUILD:8:1: no such package 'third_party/java/jbox2d': BUILD file not found on package path and referenced by '//transpiler/javatests/com/google/j2cl/transpiler/integration/box2d:box2d_j2cl'
ERROR: Analysis of target '//transpiler/javatests/com/google/j2cl/transpiler/integration/box2d_noclassmetadata_checksmin:compiled_test_bin' failed; build aborted: no such package 'third_party/java/jbox2d': BUILD file not found on package path
INFO: Elapsed time: 2.386s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (230 packages loaded, 65 targets configured)
FAILED: Build did NOT complete successfully (230 packages loaded, 65 targets configured)
    currently loading: jre/java/javaemul/internal/vmbootstrap/primitives

**Comment by solomatov** [comment]
> tests used for testing J2CL transpiler work on opensource

I understand that. 

>Don't forget that J2CL is currently in 'alpha' release for developer preview.

I also understand that. But I think making it work (or exclude some not working stuff in copybara, which you probably use) is a low hanging fruit which would make it possible for people outside of G to experiment with the tool.

**Comment by jDramaix** [comment]
> When I the command , I got the following error:

Could you open a new issue for that?

**Comment by rluble** [comment]
@solomatov, are you synced with HEAD? The changes for the integration tests went in this morning.

**Comment by solomatov** [comment]
@rluble Yes, it was close to the time which I wrote the comment. I tried it again, and it failed again.
