### ISSUE TITLE
What is the replacement for com.google.gwt.core.client.GWT 

### ISSUE THREAD

**Issue by norzak** [google/j2cl#135]
What is the replacement for com.google.gwt.core.client.GWT to instantiate a class?

**Comment by gkdn** [comment]
GWT.create is a mechanism to use something called "deferred-binding" in GWT. It is used in conjunction with code generators and gwt.xml type binding.  
Deferred doesn't exist in J2CL; you can instantiate all classes with regular constructor calls.. GWT code generators are replaced with standard Java APT code generators and gwt.xml binding is not supported.
