### ISSUE TITLE
Wasm sample broken

### ISSUE THREAD

**Issue by sdeleuze** [google/j2cl#179]
When I try to compile the Wasm sample with `bazel run samples/wasm/src/main/java/com/google/j2cl/samples/wasm:jsapp_dev_server`, I get the following error:

```
ERROR: /home/seb/wasm/j2cl/samples/wasm/src/main/java/com/google/j2cl/samples/wasm/BUILD:38:19: Compiling to WASM (stage 1) failed: (Exit 1): binaryen failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/third_party/binaryen --enable-exception-handling --enable-gc --enable-reference-types --enable-sign-ext --enable-strings --enable-nontrapping-float-to-int --nominal ... (remaining 11 arguments skipped)
Unknown option '--closed-world'
```

Binarien 111 which is the latest version seems to be used as expected:
```
bazel-out/k8-opt-exec-2B5CBBC6/bin/third_party/binaryen --version
wasm-opt version 111
```

Any chance this could be fixed?

**Comment by rluble** [comment]
I think `--closed-world` is not in the latest released version of binaryen and was added to the binaryen later. You can either build binaryen from source or remove the flag from [j2wasm_application.bzl:219](https://github.com/google/j2cl/blob/551a20e999414aee541384846f38925d1a91a34d/build_defs/internal_do_not_use/j2wasm_application.bzl#L219).

See #174

**Comment by sdeleuze** [comment]
Thanks for your feedback.

The sampe has been fixed by [Binaryen 112](https://github.com/WebAssembly/binaryen/releases/tag/version_112) kindly released by @kripken after [this discussion on Twitter](https://twitter.com/kripken/status/1624108255705460736).

As a consequence, I close this issue.
