### ISSUE TITLE
[WASM] HashMap.computeIfAbsent doesn't work as expected

### ISSUE THREAD

**Issue by treblereel** [google/j2cl#199]
The following code leads to an exception, unfortunately, because of wasm I can't provide something useful:

```
        Map<Character, List<String>> map = new HashMap<>();
        List<String> curr = map.computeIfAbsent(null, c -> new ArrayList<>());
        curr.add("test");
```

That works:

```
        Map<Character, List<String>> map = new HashMap<>();
        List<String> curr = map.computeIfAbsent('c', c -> new ArrayList<>());
        curr.add("test");
```

Looks like there is a bug in `computeValueForNullKeyIfAbsent`

bazel: 5.1
j2cl: HEAD
binyrian: 112 & 114
on osx

**Comment by gkdn** [comment]
Looks like we are missing some test coverage here. Thanks for reporting.
