### ISSUE TITLE
Create an example of how to use web APIs with j2cl

### ISSUE THREAD

**Issue by solomatov** [google/j2cl#20]
**Is your feature request related to a problem? Please describe.**
We would love to try using j2cl in external apps, but until there's an easy way to use WebAPIs, it's hard to do so. 

**Describe the solution you'd like**
It would be nice to have an example near helloworld, where some web API is used via elemental2 or other library. Initially it might contain a number of hacks, but this should be good enough for early adopter outside of Google

**Describe alternatives you've considered**
I spend some time investigating how to configure it myself, but it took too much time and I gave up.

**Comment by niloc132** [comment]
What are you asking for, specifically? Adding elemental2, jsinterop-base to the classpath for j2cl and then transpiling the necessary js from those two dependencies seems to work well in maven at least (see https://github.com/vertispan/connected/tree/j2cl). Those maven jars should work in bazel too, if you don't just depend on the github project.

Seems related to https://github.com/google/j2cl/issues/15 aside from that.

**Comment by solomatov** [comment]
@niloc132 That's great! May be I should create such an example myself.

**Comment by solomatov** [comment]
@niloc132 Concerning #15. Do I understand correctly, that if I use j2cl_import everything should work fine?

**Comment by niloc132** [comment]
I'm afraid my focus has been on getting j2cl working on environments outside of bazel (which seems successful, we have junit4, old gwttestcase, and gwt2 entrypoints working). I don't know what j2cl_import does, but from my understanding is that j2cl_library and java_library should be sufficient (since you need both bytecode and .java so that overlays and util classes can be emitted).

That said, from reading the docs I'm all but certain you don't want to use j2cl_import, it says it should only be used for annotation bytecode:

```
j2cl_import build macro

Takes nonstandard input and repackages it with names that will allow the
j2cl_import() target to be directly depended upon from j2cl_library() targets.

Should only be used for importing annotation byte code, otherwise may result
in hard to debug errors!


Example use:

j2cl_import(
  name = "Qux",
  jar = "//java/com/qux:qux_java",
)

j2cl_library(
    name = "Bar",
    srcs = glob(["Bar.java"]),
    deps = [":Qux"],  # the j2cl_import target
)
```

**Comment by solomatov** [comment]
@niloc132 Ok. I will try it when I have time. Will let you know about results of it.

**Comment by jDramaix** [comment]
@solomatov Please open an issue in [elemental2 repository](https://github.com/google/elemental2/issues) I'm adding j2cl_library rules in this repo so you can depends on directly.

**Comment by solomatov** [comment]
@jDramaix What should I write in the request there?

**Comment by jDramaix** [comment]
describe your problem :) IIUC, you want to use elemental2 with bazel and j2cl

**Comment by solomatov** [comment]
@jDramaix Ok :-) I will first try and check that it really doesn't work. I inferred from the original issue here that it doesn't work well, but it seems that it should work well.

**Comment by solomatov** [comment]
@jDramaix I had a problem and create an issue: https://github.com/google/elemental2/issues/68 Thanks.
