### ISSUE TITLE
Bazel: accidental impossible target

### ISSUE THREAD

**Issue by niloc132** [google/j2cl#201]
While there are many BUILD files that don't work in open source, a relatively recent change has added a new target that doesn't work. Bazel supports building an entire package of targets via `...`, or building all targets within a package with `*`. This has worked on the `//jre/java` BUILD file until fairly recently, but today if you try `bazel build //jre/java:*`, an error will occur:

```
ERROR: /home/colin/workspace/j2cl/jre/java/BUILD:95:16: //jre/java:javaemul/internal/WasmArray.java: missing input file '//jre/java:javaemul/internal/WasmArray.java'
ERROR: /home/colin/workspace/j2cl/jre/java/BUILD:95:16: 1 input file(s) do not exist
INFO: Elapsed time: 0.183s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
```

Investigating with bazel query shows that there is indeed a target called `//jre/java:javaemul/internal/WasmArray.java` in the project - the line number and apparent file path indicates that this is coming from here:
https://github.com/google/j2cl/blob/76bf687358b309e9feb107e79c3c50302108813c/jre/java/BUILD#L74-L93

where line 83 declares the file that doesn't exist, and the error comes from line 86.

The definition of package_sources indicates that `excludes` here is a list of labels
https://github.com/google/j2cl/blob/76bf687358b309e9feb107e79c3c50302108813c/jre/java/package_sources.bzl#L44

Apparently, by being a list of labels (rather than a string list), this means that each string must exist as a label, and seems to be implicitly created? In any case, since there is no declared target by that name, bazel assumes there must be a file at the path, and emits the above error. 

This patch tweaks how `package_sources()` is defined, to use a string_list instead, including changing how the value is iterated:
```patch
diff --git a/jre/java/package_sources.bzl b/jre/java/package_sources.bzl
index 10869b43c2..77e0005285 100644
--- a/jre/java/package_sources.bzl
+++ b/jre/java/package_sources.bzl
@@ -7,8 +7,12 @@ def _impl(ctx):
     src_jar = ctx.outputs.srcjar
     excludes = [
         x.label.name.replace("super-wasm/", "").replace("super-wasm-alt/", "")
-        for x in (ctx.attr.super_srcs + ctx.attr.excludes)
-    ]
+        for x in (ctx.attr.super_srcs)
+    ] + [
+                x.replace("super-wasm/", "").replace("super-wasm-alt/", "")
+                for x in (ctx.attr.excludes)
+            ]
+
     all_srcs = [f for f in ctx.files.srcs if not any([f.path.endswith(x) for x in excludes])]
     all_srcs += ctx.files.super_srcs
 
@@ -41,7 +45,7 @@ package_sources = rule(
     attrs = {
         "srcs": attr.label_list(mandatory = True, allow_files = [".java"]),
         "super_srcs": attr.label_list(allow_files = [".java"]),
-        "excludes": attr.label_list(allow_files = [".java"]),
+        "excludes": attr.string_list(),
         "_zip": attr.label(
             executable = True,
             cfg = "exec",
```

---

Alternatively, this might be a refactoring error - in https://github.com/google/j2cl/commit/3d123e1217 the WasmArray.java file existed and was added to the exclude list, then in https://github.com/google/j2cl/commit/ce89e5db5d the file was removed, but was still excluded. It seems to build cleanly when that label is removed.

```patch
diff --git a/jre/java/BUILD b/jre/java/BUILD
index 0e8cc1cac6..2f32be8d7d 100644
--- a/jre/java/BUILD
+++ b/jre/java/BUILD
@@ -80,7 +80,7 @@ WASM_EXCLUDED_SRCS = [
     "javaemul/internal/ArrayStamper.java",  # Unused in Wasm
     "javaemul/internal/Comparables.java",  # Unused in Wasm
     "javaemul/internal/Objects.java",  # Unused in Wasm
-    "javaemul/internal/WasmArray.java",  # Generated in Wasm.
 ]
 
 package_sources(
```

That seems like it might be the better fix? 

Unfortunately, despite recent support for tests, nothing in `//jre/javatests/` can be built or run, so I can't do a lot to validate this directly, since neither `"//javascript/tools/jscompiler/builddefs:flags.bzl"` nor `"//third_party/bazel_rules/rules_closure/closure:defs.bzl"` can be resolved (though the latter is nearly the same as `"@io_bazel_rules_closure//closure:defs.bzl"`, though `closure_js_binary()` is missing `compiler` and `extra_inputs` attributes).

**Comment by gkdn** [comment]
I've been using bazel for 10+ years but I'm seeing `:*` for the first time :) The common way to build all targets in a package is to do `//foo:all` but it looks like ":all" is not really all.

Will fix it, thanks for reporting.

**Comment by niloc132** [comment]
Thanks for the tip, `:all` might be what i've been looking for since I started using bazel, but `:*` is what I found right away (and might even have been in the initial j2cl instructions? More likely from some other bazel.build guide as I was finding my way).
