### ISSUE TITLE
Using @JsProperty for properties with periods in the name causes type errors

### ISSUE THREAD

**Issue by assafgelber** [google/j2cl#23]
Hi, thanks for your work on this project!
I'm not entirely sure whether this is a bug or a feature request, but definitely an interesting case I ran into.

**Describe the bug**

I am trying to use the (archived, yet still in prod) [Settings API in B2G](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/Settings_API) using JsInterop types. Very briefly, the [`SettingsLock#get(key)`](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/SettingsLock/get) method takes a settings key (which is generally [one of these](https://github.com/mozilla-b2g/gaia/blob/975a35c0f5010df341e96d6c5ec60217f5347412/build/config/common-settings.json)), and returns a `DOMRequest` object. If reading from settings succeeds, the request's result object will look something like this:

```javascript
"result": {
  "deviceinfo.os": "2.0.0"
}
```
So, in this case, the value I am interested in is `"2.0.0"`.

Here is a **very simplified** version of the types I'm using:
```java
// Navigator.java

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class Navigator {

    @JsProperty(name = "mozSettings")
    public native SettingsManager getSettings();
}

// SettingsManager.java

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class SettingsManager {

    @JsMethod
    public native SettingsLock createLock();
}

// SettingsLock.java

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class SettingsLock {

    @JsMethod
    public native <T> DOMRequest<T> get(String key);
}

// Callback.java

@JsFunction
public class Callback {
    public run();
}

// DOMRequest.java

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class DOMRequest<T> {

    @JsProperty
    public native T getResult();

    @JsProperty(name = "onsuccess")
    public native void setOnSuccess(Callback onSuccess);
}

// DeviceOSResult.java

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class DeviceOSResult {

    @JsProperty(name = "deviceinfo.os")
    public native String getDeviceOS();
}
```

And then I would want to use this like so:
```java
// DeviceSettings.java

public class DeviceSettings {

    public void getDeviceOS(Navigator navigator) {
        SettingsLock lock = navigator.getSettings().createLock();
        DOMRequest<DeviceOSResult> request = lock.get("deviceinfo.os");
        request.setOnSuccess(() -> {
            String os = request.getResult().getDeviceOS();
            // Do something with OS
        });
    }
}

```

This code transpiles to (simplified):

```javascript
var os = request.result.deviceinfo.os;
```

And then instead of the value, as you may expect, I get:

```
TypeError: Cannot read property 'os' of undefined
```

You can try reproduce this with the code above.

**Expected behavior**

This is definitely a strange API, and indeed it was not accepted and didn't make it's way into the spec. It is still implemented in B2G, however, and there are devices in the wild using it.

That being said, ideally, I would expect this to transpile to something like:

```javascript
var os = request.result["deviceinfo.os"];
```

However, I would be happy to hear from you all if there might be a better, simpler way of getting this value from the result object, since this is such a niche API.
So I'm happy to hear other options or discuss how to potentially fix properties like this.

Either way, thank you for you time! 💟💟💟

**Comment by tbroyer** [comment]
From my PoV this is actually a feature. You'll want to use a `JsMap` or similar here.

**Comment by assafgelber** [comment]
Thanks for your reply!
Could you point me to what exactly do you mean by `JsMap`, I couldn't find any info about apart from [this class](https://github.com/ArcBees/gwtquery/blob/master/gwtquery-core/src/main/java/com/google/gwt/query/client/js/JsMap.java) in GwtQuery. Is that what you mean?

**Comment by tbroyer** [comment]
Sorry, I actually meant `JsPropertyMap`, from jsinterop-base: https://javadoc.io/doc/com.google.jsinterop/base/1.0.0-RC1

**Comment by assafgelber** [comment]
I see, wasn't familiar with that. 
Funnily enough, as a temporary solution, before writing this issue, I did end up implementing something very similar with the JSNI for doing `return object[key];`. I was hoping there would be a solution which wouldn't require JSNI though.

Either way, gonna close this issue, but happy to hear if you have any more thoughts.
Thanks again for the help!
