### ISSUE TITLE
Which JRE classes are implemented?

### ISSUE THREAD

**Issue by sarsonj** [google/j2cl#30]
Hi,

is there somewhere described, which standard JRE classes are already included, which are planned and which not?

For example I tried ByteBuffer and and I get:

The import java.nio.ByteBuffer cannot be resolved

so that it looks like it is not there. It would be nice to have overview what is there and what not.

Thanks!

Jindrich

**Comment by niloc132** [comment]
java.nio.ByteBuffer is supported by PlayN, but PlayN hasnt done any updates to move from JSNI to JsInterop, so J2CL can't use it yet. I started the work in a branch some time ago (https://github.com/niloc132/playn/tree/jsinterop), but haven't completed it. Have been meaning to talk to them to see what approach they want to take with J2CL, and see if it might not make more sense to move java.nio.ByteBuffer and related classes to their own artifact (or into GWT's own JRE support).
