### ISSUE TITLE
How to convert arbitrary maven dependency to j2cl_library in Bazel

### ISSUE THREAD

**Issue by realityforge** [google/j2cl#36]
I am attempting to convert a simple project to j2cl using Bazel but I am unable to figure out how to turn an arbitrary dependency into a `j2cl_library`. I can not find any examples that do not define `j2cl_library` in terms of local source.

So if I have a maven dependency of my application that I want to compile against. It includes annotations that drive an annotation processor.

The dependency (that includes annotations) is declared via:

```python
maven_jar(
    name = "org_realityforge_arez_core",
    artifact = "org.realityforge.arez:arez-core:0.132",
    sha1 = "6ee17e9fa56cfac5236c3a36b9e11bc0772825fc",
)
```

The annotation processor is declared via:

```python
maven_jar(
    name = "org_realityforge_arez_processor",
    artifact = "org.realityforge.arez:arez-processor:0.132",
    sha1 = "8d81984baf6273a3f8cae8cc2701cb3807921dab",
)

java_plugin(
    name = "arez_processor",
    processor_class = "arez.processor.ArezProcessor",
    deps = ["@org_realityforge_arez_processor//jar"],
)
```

The build of my code is defined via

```python
j2cl_import(
    name = "org_realityforge_arez_core-j2cl",
    jar = "@org_realityforge_arez_core//jar",
)

j2cl_library(
    name = "react4j-todomvc-j2cl",
    srcs = glob(["src/main/java/react4j/todomvc/**/*.java"]),
    plugins = ["arez_processor"],
    deps = [
        "org_realityforge_arez_core-j2cl",
        ...
    ],
)
```

This get's my local code compiled but obviously does not j2cl compile that `arez_core` dependency. The assumption being that `j2cl_import` is only really for "annotations" and other .class file inclusions in the compile but it does not trigger a j2cl compile. So I end up with with my local source code compiled but not arez-core.

For a a simple reproduction of this issue you can see the code at

https://github.com/react4j/react4j-todomvc/tree/raw_bazel_j2cl

A log of a failed build is available at

https://travis-ci.org/react4j/react4j-todomvc/builds/500993432

It is probably fairly obvious what my problem is for a bazel user but if you could point me in the right direction that would be fasntastic.

**Comment by gkdn** [comment]
j2cl_import is not what you are looking for. It doesn't have a great name but currently j2cl_import is only for importing annotations without source and shouldn't be used for anything else.

You should get source jar for your maven target and supply that via srcs of your j2cl_library target.

**Comment by realityforge** [comment]
Much easer thanks

**Comment by swuecho** [comment]
still not that obvious to me. how to build a third part java lib, such as 'apache_common_text' to j2cl lib.

a sample would be really helpful. Thanks.

**Comment by realityforge** [comment]
Assuming a particular library is j2cl compatible it is as simple as adding the maven dependency label to `srcs` attribute. Something like:

```python

j2cl_library(
    name = "mylib-j2cl",
    srcs = ["//thirdparty:mylib"],
    deps = [
        ":javax_annotation-j2cl",
        ":gwt-javaemul-internal-annotations-j2cl",
        ":jsinterop_annotations-j2cl",
        ":jsinterop_base-j2cl",
    ],
)
```

Unfortunately I don't have a clean example in OSS world but an example I was working on is available at https://github.com/react4j/react4j-todomvc/tree/raw_bazel_j2cl 

It does not do everything "correctly" (i.e. it uses elemental2 jars shipped to maven central) and adds native js and externs locally because j2cl does not yet have an approach for working with javascript deps from maven central ... but it at least gives you an idea.

I should update it to follow some nicer conventions but I haven't quite got around to it ;)

HTH
