### ISSUE TITLE
Packaging externs and *.native.js files

### ISSUE THREAD

**Issue by realityforge** [google/j2cl#38]
Several of the libraries I am attempting to convert across to J2CL are designed as a combination of java, closure externs, closure modules and non-closure compatible javascript. In most cases the expectation is that the library will be developed and then published to some artifact repository ala Maven Central. While the producers are unlikely to be able to move to Bazel in the short term, we are hoping to move the consumers to Bazel where possible.

As an example I am going to use [react4j](https://github.com/react4j/react4j) (although we have several similar libraries). It ships a [react4j-core](https://search.maven.org/artifact/org.realityforge.react4j/react4j-core/0.121/jar) artifact which contains java that can easily be added to `srcs` in `j2cl_library` to get it transpiled. But the `*.native.js` (i.e. [ReactConfig.native.js](https://github.com/react4j/react4j/blob/master/core/src/main/java/react4j/ReactConfig.native.js)), the associated closure modules (i.e. [react4j.js](https://github.com/react4j/react4j/blob/master/core/src/main/java/react4j/react4j.js)) and the externs (i.e. [react.externs.js](https://github.com/react4j/react4j/blob/master/core/src/main/java/react4j/react.externs.js) are not included in the `j2cl_library` as the `srcs` property only seems to gather `*.java` source code.

As a result I manually extract the js, put it in the local filesystem and add it to the `srcs` using a manual process. This is obviously sub-optimal.

I am wondering what the best solution for this is?

Possibilities include:
* using `http_archive` and treating the jar as a "repository". Including a file such as `META-INF/bazel/BUILD` that declares the dependency. Seems neat if somewhat non-standard but closely aligns with the "use the repository" approach that seems to be common with the way that google works
* Updating the j2cl macro to add the `.jar` types as possible js sources
* Add another macro that does some unzipping/extracting magic to create a local repository
* Something else I have not thought of?

Or maybe I am going about this all wrong...

**Comment by gkdn** [comment]
> But the *.native.js (i.e. ReactConfig.native.js), the associated closure modules (i.e. react4j.js) and the externs (i.e. react.externs.js are not included in the j2cl_library as the srcs property only seems to gather *.java source code

'srcs' attribute supports any kind of sources. You should include all there. If your source jar has .js/.native.js sources, it is also smart enough to include those as well. 

The other 'srcs' attributes in j2cl_library (e.g. native_srcs) are old and should be removed; we just didn't have the time to remove the usages.

With bazel you don't really need to publish anything in maven sense. Here is some documentation:
https://docs.bazel.build/versions/master/external.html#depending-on-other-bazel-projects

jsinterop-base repo is same as your use case, it is just a standalone library. See the setup here:
https://github.com/google/jsinterop-base/blob/master/WORKSPACE

Inter WORKSPACE dependency in Bazel will work better over time - they are working on it but our current setup gets the job done.

If you like to version your library, you can tag to your branch and your users could use that in the url. e.g. to get a particular version of J2CL:

```
# Change me to a different tag
_J2CL_VERSION = "master"

http_archive(
    name = "com_google_j2cl",
    strip_prefix = "j2cl-%s" % _J2CL_VERSION,
    url = "https://github.com/google/j2cl/archive/%s.zip" % _J2CL_VERSION,
)

```

**Comment by realityforge** [comment]
> > But the *.native.js (i.e. ReactConfig.native.js), the associated closure modules (i.e. react4j.js) and the externs (i.e. react.externs.js are not included in the j2cl_library as the srcs property only seems to gather *.java source code
> 
> 'srcs' attribute supports any kind of sources. You should include all there. If your source jar has .js/.native.js sources, it is also smart enough to include those as well.

Perhaps I am doing it wrong but that does not seem to be the case. Adding the `*.js` code to the `srcs` attribute using glob works fine. Putting the javascript in a separate zip and including it also works fine.  Relying on it being inside the jar does not. AFAICT it is due to the line

https://github.com/google/j2cl/blob/01dd2794e0864eccdc3fcad8dc9ee6701fd33665/build_defs/internal_do_not_use/j2cl_common.bzl#L31

So no js inside the jar gets picked up. I can't rename the dependency to a zip as the `@GwtIncompatible` is not stripped and I get a different error.

It is somewhat infeasible at this time to convert the source projects (i.e. `react4j`) into a bazel project so I was hoping there would be some way that I could pull the jar from an an artifact repository and use that. I know that is not how you do it inside google but it is the more common approach outside google ;)

So looking for alternatives:

* Change the `j2cl_library` macro so that it can pick js up out of jars. It is unclear how this would impact google internal libraries and what chance I would have of getting this merged.

* Convert the jar into a "repository" and use `http_archive` to get it and provide Bazel `BUILD` file for repository (potentially from within the jar). The negative of this approach is that then the artifact is bound to a particular version of  Bazel (or range of versions depending on the features used for internal `BUILD` file).

* Add another macro that responsible for taking jar and synthesizing a `.zip` file that contains all the js files so can pass this to `srcs` attribute. This is the least elegant but more likely future proof.

* or some other strategy?

**Comment by gkdn** [comment]
If it is not working then it is probably here:

https://github.com/google/j2cl/blob/01dd2794e0864eccdc3fcad8dc9ee6701fd33665/tools/java/com/google/j2cl/tools/gwtincompatible/GwtIncompatibleStripper.java#L37

That's not how I was remembering it so I need to think if there is any good reason to have that filtering but not at this time of the day :)

> It is somewhat infeasible at this time to convert the source projects (i.e. react4j) into a bazel project 

Curious why do you think so? Maybe you are thinking you would need to 'replace' maven but you don't need to. You can keep existing setup and just add couple of Bazel rules which I'm expecting to be quite straightforward for you.

**Comment by realityforge** [comment]
> > It is somewhat infeasible at this time to convert the source projects (i.e. react4j) into a bazel project
> 
> Curious why do you think so? Maybe you are thinking you would need to 'replace' maven but you don't need to. You can keep existing setup and just add couple of Bazel rules which I'm expecting to be quite straightforward for you.

Hmm keeping the existing build system and then adding a minimal bazel overlay build may work and where that doesn't resorting to a `rules_X` that uses the binary package repository may work.

However looking at the code it still seems like a bug that js files from within an archive that is not a zip are not included. So I will leave this issue open.

The main reason we can't move move to Bazel is people and process - the normal reasons ;) We may or may not have access to the source repository for good or bad reasons, teams are unlikely to take on additional work to support multiple build systems, teams are unlikely to adopt a build system that currently has such a steep learning curve and they have an alternative that they know and works better for them (for some definition of better etc).

**Comment by gkdn** [comment]
This is now handled with j2cl_import_external; pls see the guava example: https://github.com/google/j2cl/blob/master/samples/guava/WORKSPACE

**Comment by realityforge** [comment]
Great - thanks.
