### ISSUE TITLE
Rename BUILD to BUILD.bazel

### ISSUE THREAD

**Issue by realityforge** [google/j2cl#45]
It seems that the preferred name for bazel build files is `BUILD.bazel` according to bazelbuild/bazel#4517

Would this project (and `jsinterop-generator` and `elemental2`) accept PRs that moved to the preferred build file name?

**Comment by gkdn** [comment]
These are shared internally where the file should be named "BUILD". The value add is very minimal for the extra work. So we are not planning to make a switch at the moment.
Maybe this might change in the future if the other convention gets deprecated or if we see more value in doing so.

**Comment by realityforge** [comment]
Sounds good
