### ISSUE TITLE
Integer overflow semantics are not document

### ISSUE THREAD

**Issue by ribrdb** [google/j2cl#47]
The emulation limitations doesn't mention that the behavior for integer overflow is different from java, however I hit a bug because java code was assuming that adding two ints results in a 32 bit int.

**Comment by gkdn** [comment]
I guess it was missed since it was carry over from GWT semantics. This should be definitely documented.

FWIW, we are planing to change the behavior to follow Java semantics here.

**Comment by gkdn** [comment]
J2CL now emulates correct overflow semantics for integers.
