### ISSUE TITLE
Is there a plan to support chunking?

### ISSUE THREAD

**Issue by sgammon** [google/j2cl#59]
If this question is related to build, please include version of Bazel that you are running J2CL with:
 ```
Build label: 0.27.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:03:58 2019 (1560776638)
Build timestamp: 1560776638
Build timestamp as int: 1560776638
```

I'm wondering if J2CL plans to support JS chunking? We are very happy with J2CL so far. But, if we want to build a large application and serve it efficiently, we're worried about packaging everything up in one JS target.

Surely Gmail, Calendar, and the other examples cited, must have some wiring for chunking built in. Just curious if there is a plan or ideas to do this with J2CL.

**Comment by tbroyer** [comment]
"Bundling" is not done by J2Cl, but by the Closure Compiler (or anything else that's compatible with Closure's way of loading modules).

**Comment by sgammon** [comment]
@tbroyer, yes, indeed. however, Closure Compiler won't "chunk" (bundling is another term) without proper invocation.

i know there is a CLI interface for defining chunk boundaries, and optimization passes specific to chunking. however, i do not think J2CL is equipped to invoke Closure this way.

**Comment by sgammon** [comment]
@gkdn okay but do you care if users want it? i'm currently the author of a proposal to bring this to Rules Closure. it would be useful to keep this issue open to track how it might be adopted in J2CL

https://docs.google.com/document/d/1LxcJhpv5YEWAO28SiFYdKavIkSno4I4rY8UX3w_krKg

we can't really adopt J2CL without some form of _chunking_ (it's not _bundling_ because we're splitting code here, this is the terminology the compiler uses).

**Comment by gkdn** [comment]
I closed the issue because it was a question.

Internally, our users didn't need anything beyond the chunking provided by the underlying closure rules. However internally, we didn't provide a j2cl_application rule as well (since most users didn't need such a bootstrap).
Anyway; if we need to update j2cl_application rule to adapt chunking, that's not a problem. We will be happy to do that.
