### ISSUE TITLE
Cannot pass CSS into `j2cl_application`

### ISSUE THREAD

**Issue by sgammon** [google/j2cl#60]
**Describe the bug**
The `rules_closure` package has a rule called [`closure_js_binary`](https://github.com/bazelbuild/rules_closure#closure_js_binary), which J2CL uses to build Closure JS binaries.

The [`closure_js_binary` declaration supports a CSS flag](https://github.com/bazelbuild/rules_closure#arguments-1), which [accepts a `closure_css_binary` rule](https://github.com/bazelbuild/rules_closure/blob/29ec97e7c85d607ba9e41cab3993fbb13f812c4b/closure/compiler/closure_js_binary.bzl#L284), so that style rewriting can be enabled through GSS.

When using `j2cl_application`, however, there is no `css` attribute that can be passed through to Closure. This is true also of `js_devserver`, which `j2cl_application` additionally calls into to enable local dev server support.

**To Reproduce**
1) use J2CL
2) try to pass `css` into `j2cl_application`
3) it doesn't work

**Bazel version**
Please include version of Bazel that you are running J2CL with:
```
Build label: 0.27.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:03:58 2019 (1560776638)
Build timestamp: 1560776638
Build timestamp as int: 1560776638
```

**Expected behavior**
1) it shouldn't eat arguments you pass through to other libraries?
2) but it does?

**Comment by sgammon** [comment]
hello esteemed J2CL authors, is there any update on this?

**Comment by gkdn** [comment]
Fixed in https://github.com/google/j2cl/pull/61
