### ISSUE TITLE
j2cl_workspace.bzl: Make GWT dependency reproducible

### ISSUE THREAD

**Issue by factuno-db** [google/j2cl#66]
**Is your feature request related to a problem? Please describe.**
I spent half an hour today to find the source of a mysterious NullPointerException-related error that appeared after upgrading to the latest commit. When trying to build a minimal testcase for a bug report. the error disappeared.

Turns out: GWT has also updated to make this work, yet Bazel still had the old GWT tarball for "https://gwt.googlesource.com/gwt/+archive/master.tar.gz" (https://github.com/google/j2cl/blob/master/build_defs/internal_do_not_use/j2cl_workspace.bzl#L149) in its cache. 

**Describe the solution you'd like**
Make the GWT dependency somehow reproducible.

**Describe alternatives you've considered**
Running `bazel clean --expunge` every time a J2CL-related problem occurs on all machines.

**Additional context**

**Comment by niloc132** [comment]
Worth pointing out that rather than `clean --expunge`, the `sync` command is now available for a cleaner workaround.
