### ISSUE TITLE
helloworld_dev_server and helloworld_dev don't generate source maps

### ISSUE THREAD

**Issue by johnthuss** [google/j2cl#72]
**Describe the bug**
No source map is generated when running the helloworld_dev_server task or the helloworld_dev task. 

**To Reproduce**
`cd samples/helloworld`
`ibazel run src/main/java/com/google/j2cl/samples/helloworld:helloworld_dev_server`

Navigating to the source map's url (http://localhost:6006/HelloWorld.js.map) shows this error message instead of a source map:
`"No srcs found in transitive closure with path component prefix matching request path."`

Similarly, a dev build using `bazel build src/main/java/com/google/j2cl/samples/helloworld:helloworld_dev` generates an ***empty*** file for the source map:
`bazel-bin/src/main/java/com/google/j2cl/samples/helloworld/helloworld_dev.js.map`

**Bazel version**
Build label: 1.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 21 08:47:13 2019 (1571647633)
Build timestamp: 1571647633
Build timestamp as int: 1571647633

**Expected behavior**
I'd like to have source maps for my J2CL projects during development to aid in debugging. Without this, it is a step backwards from GWT 2.

**Comment by gkdn** [comment]
Thanks for the detailed report.

This is actually already tracked in https://github.com/google/j2cl/issues/10.
