### ISSUE TITLE
javax.annotation emulation not copied from GWT

### ISSUE THREAD

**Issue by niloc132** [google/j2cl#73]
While the j2cl-maven-plugin explicitly didn't support past java 8, we were able to add the jsr250 jar to the classpath that j2cl takes so that it could get `javax.annotation.Generated`, this doesn't work in java9+. Some annotation processors when running java9+ automatically switch to `javax.annotation.processing.Generated`, which isn't published in any annotation jar that I can find, but is assumed to be in the JRE.

See https://github.com/google/dagger/issues/880 as an example of this - none of the annotation processors I could find inside of j2cl seem to emit either annotation.

---

The most straightforward solution appears to be that the jre.jar needs to include this, as gwt2 does. Presently, the mirroring rule only copies the `java.*` emulation, so this needs to be expanded to `javax.*` as well. 

As I understand bazel, this first requires a change to be made to gwt, something like adding this to `user/BUILD.bazel`, matching the existing java_emul filegroup:
```
filegroup(
    name = "javax_emul",
    srcs = glob(["super/com/google/gwt/emul/javax/**/*.java"]),
)
```

With that change made, a new alias can be added in j2cl's `third_party/BUILD`, like this:
```
alias(
    name = "gwt_javax_emul",
    actual = "@org_gwtproject_gwt//user:javax_emul",
)
```
and then also update `jre/java:jre` to include that target as an entry in `mirrored_files`.

---

If approved, I'll start the change on gwt2 so that we can consider this change here in j2cl as well? Alternatively, if there is a deliberate reason that these are not included in jre.jar, I would still like to add this target to gwt (or consider another approach that you would accept), so that external users of j2cl are able to use dagger2 and other annotation processors in their projects, even under java9+.

**Comment by gkdn** [comment]
Pls just update 'java_emul' in user/BUILD.bazel to include 'super/com/google/gwt/emul/javax/**/*.java' in srcs.

@rluble  do you anticipate any problems with this?

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/c/gwt/+/22160 as a draft to address this.

**Comment by niloc132** [comment]
Any further thoughts on the proposed change to gwt's BUILD.bazel file?

**Comment by jDramaix** [comment]
the change in GWT has been submitted so I think we can close this issue
