### ISSUE TITLE
Can't build J2CL app with JDK 11 toolchain

### ISSUE THREAD

**Issue by sgammon** [google/j2cl#77]
**Describe the bug**
I am building my J2CL app within a codebase that must also support Java 11, for the server-side components. However, when I change my Java toolchain to JDK11, J2CL fails to run properly.

**To Reproduce**
1) Clone J2CL
2) Go into the example directory (cd `samples/helloworld`)
3) Run `echo "2.0.0" > .bazelversion"`
4) Rename `WORKSPACE.remote` > `WORKSPACE` and `WORKSPACE` > `WORKSPACE.local`
5) Build with regular flags first, observe that it completes (`bazelisk build //...`)
6) Run `bazelisk build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //...`
7) See error:
```
➜  helloworld git:(473aa0a2e) ✗ bazelisk build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //...
DEBUG: Rule 'com_google_j2cl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "cae6e4ffee354e9cc0fbb440a1b0898b1ab587a8dfab505782d220aa2e85a3fc"
DEBUG: Call stack for the definition of repository 'com_google_j2cl' which is a http_archive (rule definition at /private/var/tmp/_bazel_sam/f203f916dd852e7c2460b49941242252/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /Volumes/PITBULL/Vault/GUST/vendor/bazel/j2cl/samples/helloworld/WORKSPACE:6:1
INFO: Build option --java_toolchain has changed, discarding analysis cache.
INFO: Analyzed 10 targets (0 packages loaded, 2054 targets configured).
INFO: Found 10 targets...
ERROR: /private/var/tmp/_bazel_sam/f203f916dd852e7c2460b49941242252/external/com_google_j2cl/jre/java/BUILD:59:1: Building external/com_google_j2cl/jre/java/libjre_bootclasspath.jar (6 source files) failed (Exit 1)
external/com_google_j2cl/jre/java/javasynth/LambdaMetafactory.java:14: error: package exists in another module: java.base
package java.lang.invoke;
^
external/com_google_j2cl/jre/java/javasynth/MethodHandle.java:14: error: package exists in another module: java.base
package java.lang.invoke;
^
external/com_google_j2cl/jre/java/javasynth/MethodHandles.java:14: error: package exists in another module: java.base
package java.lang.invoke;
^
external/com_google_j2cl/jre/java/javasynth/MethodType.java:14: error: package exists in another module: java.base
package java.lang.invoke;
^
external/com_google_j2cl/jre/java/javasynth/NoSuchFieldError.java:14: error: package exists in another module: java.base
package java.lang;
^
external/com_google_j2cl/jre/java/javasynth/SerializedLambda.java:14: error: package exists in another module: java.base
package java.lang.invoke;
^
INFO: Elapsed time: 2.352s, Critical Path: 1.67s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully
```

**Bazel version**
`2.0.0`

**Expected behavior**
I would expect it to at least build, even if it must enforce Java 8 language semantics. Perhaps there would be a way to force a JDK8 toolchain for J2CL targets?

**Comment by sgammon** [comment]
FYI this can be fixed with the following in `.bazelrc`:
`build --javacopt="-source 8 -target 8 -encoding UTF-8"`

but obviously that opts out of all JDK11 language features, and targeting, codebase-wide (AFAIK).

**Comment by niloc132** [comment]
Note that this is likely intrinsic to bazel (and how it builds the `//jre/java:jre_bootclasspath` java_library) and not j2cl, since repackaged j2cl works in maven under java11, 13 once first built with java 8. As a possible workaround, is there a bazel-ism for "build this `java_library(...)` with java8, no matter what the local toolchain is set to?" Might be analogous to just making the jar, and then referencing it as if it were external?

**Comment by sgammon** [comment]
@niloc132 perhaps J2CL could inject `-source 8 -target 8` with [`java_package_configuration`](https://docs.bazel.build/versions/master/be/java.html#java_package_configuration)?

If I'm not mistaken, the injection could perhaps occur [here](https://github.com/google/j2cl/blob/29f2eb8570d5274959d606647284cc3558790a40/build_defs/internal_do_not_use/BUILD#L47-L50), where J2CL defines its default Java toolchain?

i'll give it a try locally and report back

**Comment by sgammon** [comment]
@niloc132 no such luck :( it still fails with the same error, after amending that file as below:
```starlark
package_group(
    name = "j2cl_java_packages",
    packages = [
        "//jre/...",
        "//tools/...",
    ],
)

java_package_configuration(
    name = "j2cl_java_config",
    packages = [":j2cl_java_packages"],
    javacopts = ["-source 8", "-target 8"],
)

default_java_toolchain(
    name = "j2cl_java_toolchain",
    bootclasspath = ["//jre/java:libjre_bootclasspath.jar"],
    package_configuration = [":j2cl_java_config"],
)
```

**Comment by gkdn** [comment]
We need to take a look and figure out what to do here.
For now if you need a quick workaround, you can get the jar output for jre_bootclasspath from java 8 build and java_import that file.

**Comment by niloc132** [comment]
For a canned copy, we already publish this as https://repo.vertispan.com/j2cl/com/vertispan/j2cl/javac-bootstrap-classpath/0.6-SNAPSHOT/ (assuming it doesn't change much, and so far it hasn't).

**Comment by sgammon** [comment]
@gkdn / @niloc132 would i use that workaround on my j2cl fork, by changing the `bootclasspath` of the `default_java_toolchain` for J2CL (like above), or is there a way to do that without code changes (i.e. via flags or some other mechanism)?

**Comment by gkdn** [comment]
In your fork, you can put the jar file under jre/java/jre_bootclasspath.jar and then replace following line with java_import of the jar file:
https://github.com/google/j2cl/blob/3e0fb7ad9419ae833167cc0f177c494460c7893b/jre/java/BUILD#L59

**Comment by sgammon** [comment]
thank you very much everyone for your help, that got it working! :)

**Comment by gkdn** [comment]
This should be working out of the box so closing the issue.
