### ISSUE TITLE
Packaging J2clCommandLineRunner as a standalone binary

### ISSUE THREAD

**Issue by bugok** [google/j2cl#78]
I'd like to build `j2cl` as a standalone binary to be used in a non-bazel build system ([buck](https://buck.build/)). I fond that it will probably be easiest to build j2cl with bazel, get the binary and use that in buck (as opposed to building j2cl in buck and using the build target).  

The issue I'm encountering is the size of the `runfiles` - it's more than 500MB, which seems like a lot to include in a single cli tool, Also, from what I understand from the documentation, those runfiles are needed in order to run `J2clCommandLineRunner`.

I'm new to bazel and j2cl, so I might be doing something wrong. Here's what I'm doing:

```
JC2CL_DIR=/data/users/${USER}/j2cl_build
mkdir $JC2CL_DIR
cd $JC2CL_DIR

git clone https://github.com/google/j2cl.git --depth=1

# Build

cd $JC2CL_DIR/j2cl

bazel build transpiler/java/com/google/j2cl/transpiler:J2clCommandLineRunner

# Put the result files in a single place
OUT_DIR=$JC2CL_DIR/out
mkdir -p $OUT_DIR
cp ./bazel-bin/transpiler/java/com/google/j2cl/transpiler/J2clCommandLineRunner $OUT_DIR
cp ./bazel-bin/transpiler/java/com/google/j2cl/transpiler/J2clCommandLineRunner.runfiles $OUT_DIR -L -r
```

Note the `-L` when copying the runfiles - as I can't rely on cache - as I want to distribute this binary to other machines. 

```
$ cd out
$ du . -sh
582M	.
$ ls -l
total 16
-r-xr-xr-x. 1 XXX users 14223 Feb  2 22:38 J2clCommandLineRunner
drwxr-xr-x. 1 XXX users  1118 Feb  2 22:38 J2clCommandLineRunner.runfiles
$
```

Am I doing something wrong? Is there a better way to package `J2clCommandLineRunner`?

Thanks!

If this question is related to build, please include version of Bazel that you are running J2CL with:
 ``` $ bazel version```

```
$ bazel version
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
```

**Comment by bugok** [comment]
@cgrushko helped me look at the output and we realized that: 
- I could build the `J2clCommandLineRunner_deploy.jar` rule and use that jar, alongside with the wrapper script. 
- The runfiles include a copy of the JRE, which we don't (really?) need. 
- I edited the `J2clCommandLineRunner` script to remove the need of the runtime files as well as set the `JAVABIN` variable to `$(which java)`. 

This got me here: 

```
$ ll
total 26424
-r-x--x--x. 1 XXX users    14177 Feb  3 03:48 J2clCommandLineRunner
-r-xr-xr-x. 1 XXX users 27040744 Feb  3 03:48 J2clCommandLineRunner_deploy.jar
$ du . -sh
26M	.
$ ./J2clCommandLineRunner --singlejar
Error: Argument "<source files>" is required
Usage: j2cl <options> <source files>
use -help for a list of possible options
1 error(s), 0 warning(s).
$
```

Maybe some of my assumptions are wrong here - but maybe this is good enough. 

Closing the issue.

**Comment by gkdn** [comment]
java_binary's deploy target is the one used for deployment:
https://docs.bazel.build/versions/2.0.0/tutorial/java.html#package-a-java-target-for-deployment

Also see:
https://docs.bazel.build/versions/master/be/java.html#java_binary_implicit_outputs

w.r.t size:
J2CL deps are not fine tuned for open-source and brings whole maven dependencies into deployment jar. This could be optimized but wasn't a concern for us so far.
