### ISSUE TITLE
ETA for v1 and meaning of "alpha" version

### ISSUE THREAD

**Issue by chipilov** [google/j2cl#86]
Hello J2CL team,

I have a couple of questions related to the following caveats/disclaimers in the documentation page:

> J2CL is production ready and actively used by many of Google's products, but the process of adapting workflows and tooling for the open-source version is not yet finalized...

> J2CL is not an official Google product and is currently in 'alpha' release for developer preview.

1. Can you provide an ETA for the release of beta and, more importantly, official v1?

2. Given the first quote above, can we assume that the "alpha" label only refers to the missing tooling while the quality of the generated JS code can be considered production-ready? That is, if one was able to put together the necessary tooling/build workflow, can one rely on the generated JS code for production purposes?

Thank you.

**Comment by gkdn** [comment]
> Given the first quote above, can we assume that the "alpha" label only refers to the missing tooling while the quality of the generated JS code can be considered production-ready? That is, if one was able to put together the necessary tooling/build workflow, can one rely on the generated JS code for production purposes?

Exactly. The code is production ready and battle tested with Google Apps for years. Only open-source tooling is missing some workflows.

> Can you provide an ETA for the release of beta and, more importantly, official v1?

At the moment we are only planning to do dated releases (which should start soon) instead of semantic versioning like v1 and make more tools work over time.
Unfortunately I cannot give a timeline for all tools to be ready since our work for open-source tooling on and off

**Comment by chipilov** [comment]
Thank you, Goktug.

If I may, I'd like to ask а couple of follow-ups before closing the issue: 

1. Do you have a plan/roadmap about how to release improvements to the transpiler itself? That is, if we put the tooling to the side, do you plan to have regular releases with improvements in the transpiler?

2. Is this version of J2CL (ignore the tooling) the same as the one used inside Google? If not, can you give us a rough idea of how the two differ?

**Comment by rluble** [comment]
> 2. Is this version of J2CL (ignore the tooling) the same as the one used inside Google? If not, can you give us a rough idea of how the two differ?

The github repo is updated at the same time as our internal repo. The versions are exactly the same. There are only minor differences  in our integration with internal tooling but those are not related to the transpiler per se.

Tooling on the open source part of our project would definitely benefit from community contributions.

**Comment by gkdn** [comment]
> 1. Do you have a plan/roadmap about how to release improvements to the transpiler itself? That is, if we put the tooling to the side, do you plan to have regular releases with improvements in the transpiler?

Like @rluble pointed; all our improvements for released code are in sync and you are getting the improvement at the same time as Google gets.

**Comment by sgammon** [comment]
@gkdn I am currently authoring a framework that integrates with J2CL, thank you for all of your hard work

as you prepare for, and begin to implement, this release timeline, is there any way we could get a wiki page up, or some kind of tracker to see progress/roadmap items?

**Comment by gkdn** [comment]
Added https://github.com/google/j2cl/issues/93
