### ISSUE TITLE
Add WebAssembly Support

### ISSUE THREAD

**Issue by sirinath** [google/j2cl#88]
With WebAssembly getting a lot of traction is it possible to have 2 back ends. One for JS and another for WA.

**Comment by niloc132** [comment]
Keep in mind that wasm still has no GC, so it might not be a terribly natural fit for a language like Java, which assumes GC. Also consider [TeaVM's very experimental wasm support](https://github.com/konsoletyper/teavm/#webassembly) as another way to consider turning your Java into wasm.

**Comment by gkdn** [comment]
We are not planning to have WebAssembly support until it is practical for our use cases; for that at minimal we need GC and better JavaScript interop story to be available in WebAsssembly.

**Comment by gkdn** [comment]
(Keeping open track future requests)

**Comment by unnati914** [comment]
I can work on this

**Comment by gkdn** [comment]
We actually implemented experimental WASM support.
(This is not good for production use, it is currently useful for Chrome/V8 team could have real world data to iterate on WASM GC specification)

**Comment by gkdn** [comment]
This has been in production quite a while and we put samples in place. All necessary W3C spec work is completed so closing this issue issue now.

**Comment by bertung** [comment]
Will you add support for WasmGC?
