### ISSUE TITLE
Project requires Bazel 2.2.0 which does not exist

### ISSUE THREAD

**Issue by Artur-** [google/j2cl#91]
**Describe the bug**
There is no Bazel 2.2.0 in npm https://www.npmjs.com/package/@bazel/bazel
2.1.0 is the latest

**To Reproduce**
Follow the first step of "getting started"

```
npm install -g @bazel/bazel@2.2.0
```

**Comment by tbroyer** [comment]
The latest Bazel version is 3.1: https://blog.bazel.build/2020/04/21/bazel-3-1.html
2.2 was released on March 3rd.
Apparently they're no longer pushed as NPM packages though… Time to use Bazelisk to autoinstall Bazel?

**Comment by gkdn** [comment]
We are updating our instructions to use [bazelisk](https://github.com/bazelbuild/bazelisk). Please use it instead.
